version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    command: yarn start
    volumes:
      - ./frontend/react-app:/frontend
    ports:
      - "3000:3000"
    env_file:
      - ".env"
    networks:
      - mynetwork
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./backend:/backend/
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
